wandb_version: 1

activation_func:
  value: relu
batch_size:
  value: 8
criterion:
  value: cossim
embedding_size:
  value: 4
epochs:
  value: 2000
learning_rate:
  value: 0.01
momentum:
  value: 0.01
n_nodes_fc1:
  value: 512
n_nodes_fc2:
  value: 256
optimizer:
  value: adam
output_activation_func:
  value: softmax
weight_decay:
  value: 0
