wandb_version: 1

activation_func:
  value: relu
batch_size:
  value: 1
criterion:
  value: mse
embedding_size:
  value: 2
epochs:
  value: 100000
learning_rate:
  value: 0.001
momentum:
  value: 0.9
n_nodes_fc1:
  value: 512
n_nodes_fc2:
  value: 256
optimizer:
  value: sgd
output_activation_func:
  value: softmax
weight_decay:
  value: 0.005
