wandb_version: 1

batch_size:
  value: 8
criterion:
  value: mse
embedding_size:
  value: 4
epochs:
  value: 10000
learning_rate:
  value: 1.0e-09
momentum:
  value: 0.1
n_nodes_fc1:
  value: 1024
n_nodes_fc2:
  value: 256
optimizer:
  value: rmsprop
weight_decay:
  value: 0.005
