wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.8.2
      5: 0.10.15
batch_size:
  desc: null
  value: 124
learning_rate:
  desc: null
  value: 1.0e-12
momentum:
  desc: null
  value: 0.1
n_epochs:
  desc: null
  value: 100
weight_decay:
  desc: null
  value: 0.0001
