wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 1
      - 5
      4: 3.6.9
      5: 0.10.18
batch_size:
  desc: null
  value: 1
criterion:
  desc: null
  value: cossim
embedding_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 1000000
learning_rate:
  desc: null
  value: 1.0e-12
momentum:
  desc: null
  value: 0.001
n_nodes_fc1:
  desc: null
  value: 1024
n_nodes_fc2:
  desc: null
  value: 256
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.005
