wandb_version: 1

batch_size:
  value: 8
criterion:
  value: dice
embedding_size:
  value: 64
epochs:
  value: 500
learning_rate:
  value: 1.0e-14
momentum:
  value: 0.1
n_nodes_fc1:
  value: 1024
n_nodes_fc2:
  value: 128
optimizer:
  value: adam
weight_decay:
  value: 0
