wandb_version: 1

batch_size:
  value: 256
embedding_size:
  value: 8
epochs:
  value: 100
learning_rate:
  value: 1.0e-10
momentum:
  value: 0
n_nodes_fc1:
  value: 64
n_nodes_fc2:
  value: 32
optimizer:
  value: adam
weight_decay:
  value: 0
