wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 1
      - 5
      4: 3.6.9
      5: 0.10.18
activation_func:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 1
criterion:
  desc: null
  value: mse
embedding_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 10000
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
n_nodes_fc1:
  desc: null
  value: 512
n_nodes_fc2:
  desc: null
  value: 256
optimizer:
  desc: null
  value: sgd
output_activation_func:
  desc: null
  value: softmax
weight_decay:
  desc: null
  value: 0.005
