wandb_version: 1

batch_size:
  value: 64
criterion:
  value: mse
embedding_size:
  value: 64
epochs:
  value: 500
learning_rate:
  value: 0.001
momentum:
  value: 0
n_nodes_fc1:
  value: 1024
n_nodes_fc2:
  value: 128
optimizer:
  value: adam
weight_decay:
  value: 0.005
