wandb_version: 1

batch_size:
  value: 64
criterion:
  value: dice
embedding_size:
  value: 32
epochs:
  value: 500
learning_rate:
  value: 1.0e-09
momentum:
  value: 0.1
n_nodes_fc1:
  value: 1024
n_nodes_fc2:
  value: 128
optimizer:
  value: rmsprop
weight_decay:
  value: 0
