wandb_version: 1

batch_size:
  value: 1
criterion:
  value: cossim
embedding_size:
  value: 8
epochs:
  value: 1000000
learning_rate:
  value: 1.0e-12
momentum:
  value: 0.01
n_nodes_fc1:
  value: 1024
n_nodes_fc2:
  value: 256
optimizer:
  value: rmsprop
weight_decay:
  value: 0
