wandb_version: 1

batch_size:
  value: 64
criterion:
  value: mse
embedding_size:
  value: 32
epochs:
  value: 500
learning_rate:
  value: 1.0e-12
momentum:
  value: 0.9
n_nodes_fc1:
  value: 1024
n_nodes_fc2:
  value: 256
optimizer:
  value: sgd
weight_decay:
  value: 0.005
