wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.2
      5: 0.10.15
batch_size:
  desc: null
  value: 256
embedding_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 1.0e-10
momentum:
  desc: null
  value: 0
n_nodes_fc1:
  desc: null
  value: 128
n_nodes_fc2:
  desc: null
  value: 64
optimizer:
  desc: null
  value: rmsprop
weight_decay:
  desc: null
  value: 0.05
