wandb_version: 1

batch_size:
  value: 256
embedding_size:
  value: 32
epochs:
  value: 1000
learning_rate:
  value: 1.0e-10
momentum:
  value: 0
n_nodes_fc1:
  value: 256
n_nodes_fc2:
  value: 128
optimizer:
  value: adam
weight_decay:
  value: 0.0005
